CREATE TABLE CAPA(
	id SERIAL PRIMARY KEY,
	url_imagem TEXT,
	alt text
);

CREATE TABLE MUSICA(
	id SERIAL PRIMARY KEY,
	nome VARCHAR(30),
	id_album INT,
	album INT
);

CREATE TABLE ARTISTA(
	id SERIAL PRIMARY KEY,
	nome VARCHAR(30),
	ouvintes_mensais DECIMAL CHECK (ouvintes_mensais >= 0),
	descricao TEXT,
	ano_debut INT,
	id_gravadora INT
);

CREATE TABLE ALBUM(
	id SERIAL PRIMARY KEY,
	nome VARCHAR(50),
	data_lancamento DATE,
	quantidade_faixas INT,
	id_artista INT,
	id_capa INT,

	CONSTRAINT ALBUM_FK_ID_ARTISTA FOREIGN KEY (id_artista) REFERENCES ARTISTA (id),
	CONSTRAINT ALBUM_FK_ID_CAPA FOREIGN KEY (id_capa) REFERENCES CAPA(id)
);

ALTER TABLE MUSICA
	ADD CONSTRAINT MUSICA_FK_ID_ALBUM FOREIGN KEY (id_album) REFERENCES ALBUM (id);

CREATE TABLE GRAVADORA(
	id SERIAL PRIMARY KEY,
	nome VARCHAR(30)
);

ALTER TABLE ARTISTA
	ADD CONSTRAINT ARTISTA_FK_ID_GRAVADORA FOREIGN KEY (id_gravadora) REFERENCES GRAVADORA(id);

CREATE TABLE PLAYLIST(
	id SERIAL PRIMARY KEY,
	nome VARCHAR(30),
	data_criacao DATE DEFAULT CURRENT_DATE,
	id_usuario INT
);

CREATE TABLE USUARIO(
	id SERIAL PRIMARY KEY,
	nome VARCHAR(30),
	apelido VARCHAR(30) UNIQUE,
	id_plano_assinatura INT
);

CREATE TABLE PLANO_ASSINATURA(
	id SERIAL PRIMARY KEY,
	nome VARCHAR(30),
	valor DECIMAL,
	descricao TEXT
);

ALTER TABLE PLAYLIST ADD CONSTRAINT PLAYLIST_FK_ID_USUARIO FOREIGN KEY (id_usuario) REFERENCES USUARIO(id);

ALTER TABLE USUARIO ADD CONSTRAINT PLAYLIST_FK_ID_PLANO_ASSINATURA FOREIGN KEY (id_plano_assinatura) REFERENCES PLANO_ASSINATURA(id);

CREATE TABLE MUSICA_PLAYLIST(
	id_playlist INT,
	id_musica INT,

	CONSTRAINT ID_PLAYLIST_MUSICA FOREIGN KEY (id_playlist) REFERENCES PLAYLIST(id),
	CONSTRAINT ID_MUSICA_PLAYLIST FOREIGN KEY (id_musica) REFERENCES MUSICA(id),
	PRIMARY KEY (id_playlist, id_musica)
);

CREATE TABLE LETRA(
	id SERIAL PRIMARY KEY,
	idioma VARCHAR(15),
	letra_original TEXT,
	traducao_BR TEXT,
	id_musica INT,

	CONSTRAINT LETRA_ID_MUSICA FOREIGN KEY (id_musica) REFERENCES MUSICA(id)
);

CREATE TABLE AVALIACAO(
	quantidade_estrelas DECIMAL CHECK (quantidade_estrelas IN (0, 0.5, 1, 1.5, 2, 2.5, 3, 3.5, 4, 4.5, 5)),
	comentario TEXT,
	id_album INT,
	id_usuario INT,

	CONSTRAINT AVALIACAO_FK_ID_ALBUM FOREIGN KEY (id_album) REFERENCES ALBUM(id),
	CONSTRAINT AVALIACAO_FK_ID_USUARIO FOREIGN KEY(id_usuario) REFERENCES USUARIO(id),
	PRIMARY KEY(id_album, id_usuario)
);

CREATE TABLE FAIXA(
	id SERIAL PRIMARY KEY,
	numero INT,
	id_album INT,

	CONSTRAINT FAIXA_FK_ID_ALBUM FOREIGN KEY(id_album) REFERENCES ALBUM(id)
);

CREATE TABLE SINGLE(
	nome VARCHAR(30),
	data_lancamento DATE DEFAULT CURRENT_DATE,
	id_faixa INT PRIMARY KEY,
	id_capa INT,

	CONSTRAINT SINGLE_FK_ID_FAIXA FOREIGN KEY (id_faixa) REFERENCES FAIXA(id),
	CONSTRAINT SINGLE_FK_ID_CAPA FOREIGN KEY (id_capa) REFERENCES CAPA(id)
);

CREATE TABLE PREVIEW(
	id SERIAL PRIMARY KEY,
	url_audio TEXT,
	id_musica INT,

	CONSTRAINT PREVIEW_FK_ID_MUSICA FOREIGN KEY (id_musica) REFERENCES MUSICA(id)
);

CREATE TABLE MEMBRO(
	id SERIAL PRIMARY KEY,
	nome VARCHAR(30),
	nascimento INT,
	nacionalidade VARCHAR(30),
	id_artista INT,

	CONSTRAINT MEMBRO_FK_ID_ARTISTA FOREIGN KEY (id_artista) REFERENCES ARTISTA(id)
);

CREATE TABLE GENERO(
	id SERIAL PRIMARY KEY,
	nome VARCHAR(20)
);

CREATE TABLE ARTISTA_GENERO(
	id_artista INT,
	id_genero INT,

	CONSTRAINT ARTISTA_GENERO_FK_ID_ARTISTA FOREIGN KEY (id_artista) REFERENCES ARTISTA(id),
	CONSTRAINT ARTISTA_GENERO_FK_ID_GENERO FOREIGN KEY (id_genero) REFERENCES GENERO(id),
	PRIMARY KEY (id_artista, id_genero)
);

CREATE TABLE ARTISTA_MUSICA(
	id_artista INT,
	id_musica INT,
	tipo_participacao VARCHAR(20),

	CONSTRAINT ARTISTA_MUSICA_FK_ID_ARTISTA FOREIGN KEY (id_artista) REFERENCES ARTISTA(id),
	CONSTRAINT ARTISTA_MUSICA_FK_ID_MUSICA FOREIGN KEY (id_musica) REFERENCES MUSICA(id)
);
